### ISSUE TITLE
Переделать квартальный план в диаграмму Ганта

### ISSUE THREAD

**Issue by neevink** [Education-bot/chatbot_backend#24]

**Comment by neevink** [comment]
@nastyane 
Настя, сюда бы скриншот диаграммы ганта. И ссылку добавить на неё на вики.

**Comment by nastyane** [comment]
wiki: https://www.openproject.org/docs/user-guide/wiki/


![диаграмма](https://github.com/user-attachments/assets/1c0164cf-3ea7-4140-943a-3f5e1605835f)
