### ISSUE TITLE
Проанализировать задаваемые в VK сообществе вопросы, выделить и классифицировать наиболее часто встречающиеся. Подготовить эталонные ответы в файле

### ISSUE THREAD

**Issue by TheBigBagrovski** [Education-bot/chatbot_backend#30]

**Comment by neevink** [comment]
Настя и Матвей посмотрели: https://docs.google.com/document/d/1EEZxgsmY5rCbLLiSdOa_TF6-M6H-js2U8cgR4mN_Apo/edit?tab=t.0

**Comment by TheBigBagrovski** [comment]
На большинство вопросов получилось найти ответ, Настя уточнит у куратора по поводу ответов на оставшиеся
