### ISSUE TITLE
Проанализировать применимость YandexGPT API

### ISSUE THREAD

**Issue by neevink** [Education-bot/chatbot_backend#7]

**Comment by all-mute** [comment]
https://github.com/all-mute/openai2yandex_translator

**Comment by neevink** [comment]
Почитал доку YandexGPT API 

Разобрался, что дообучить модель новой информации, например базе знаний службы поддержки, не получится [(пруф)](https://yandex.cloud/ru/docs/datasphere/tutorials/yagpt-tuning).

Но зато в зампросе можно просить сформулировать ответ или вытащить из текста нужный ответ на вопрос, пруф: ![Image](https://github.com/user-attachments/assets/6f25044a-9ab1-41cb-b8df-845b2f237323)

**Comment by all-mute** [comment]
Привет! До конца года завезем лору, можно будет дообучать знаниями.

**Comment by neevink** [comment]
Зато классификатор на основе YandexGPT неплохо себя показывает, протестировать можно не через UI, а через запрос:

```
IAM_TOKEN=$(yc iam create-token)

curl -s -X POST https://llm.api.cloud.yandex.net/foundationModels/v1/fewShotTextClassification -H "Content-Type: application/json" -H "Authorization: Bearer $IAM_TOKEN" -d '{
  "modelUri": "cls://<PASTE_FOLDER_ID_HERE>/yandexgpt/latest",
  "taskDescription": "Классификация вопросов об онлайн-курсах",
  "labels": [
    "как и в каком формате сдаётся домашнее задание",
    "какие есть предметы и задания на платформе",
    "когда будет следующее занятие по рассписанию"
  ],
  "text": "Здравствуйте, а в каком формате дз отправлять?"
}' | jq
{
  "predictions": [
    {
      "label": "как и в каком формате сдаётся домашнее задание",
      "confidence": 0.9999996423721313
    },
    {
      "label": "какие есть предметы и задания на платформе",
      "confidence": 3.493512963359535e-07
    },
    {
      "label": "когда будет следующее занятие по рассписанию",
      "confidence": 4.923702071057967e-11
    }
  ],
  "modelVersion": "07.03.2024"
}

```

**Comment by neevink** [comment]
https://yandex.cloud/ru/docs/foundation-models/concepts/classifier/?utm_referrer=https%3A%2F%2Fyandex.ru%2F
